#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SERVER_REMOTE_DEFAULT="flageemonitor-server"
SERVER_BRANCH_DEFAULT="main"
PUSH_CHANGES=0
DRY_RUN=0
SERVER_REMOTE="${SERVER_REMOTE_DEFAULT}"
SERVER_BRANCH="${SERVER_BRANCH_DEFAULT}"

usage() {
  cat <<USAGE
Uso:
  $0 [--server-remote NAME] [--server-branch BRANCH] [--push] [--dry-run]

Descricao:
  Promove conteudo interno do server para o repositório flageemonitor-server
  com allowlist e validacoes de seguranca.

Opcoes:
  --server-remote NAME   Remote git de destino (default: ${SERVER_REMOTE_DEFAULT})
  --server-branch NAME   Branch de destino (default: ${SERVER_BRANCH_DEFAULT})
  --push                 Faz push ao final (default: desabilitado)
  --dry-run              Gera staging e validacoes, sem commit
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server-remote)
      SERVER_REMOTE="$2"
      shift 2
      ;;
    --server-branch)
      SERVER_BRANCH="$2"
      shift 2
      ;;
    --push)
      PUSH_CHANGES=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Argumento invalido: $1"
      usage
      exit 1
      ;;
  esac
done

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Comando obrigatorio ausente: $1"; exit 1; }
}

require_cmd git
require_cmd rsync
require_cmd rg

if ! git -C "$ROOT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Diretorio raiz nao e um repositorio git valido: $ROOT_DIR"
  exit 1
fi

SERVER_URL="$(git -C "$ROOT_DIR" remote get-url "$SERVER_REMOTE" 2>/dev/null || true)"
if [[ -z "$SERVER_URL" ]]; then
  echo "Remote '$SERVER_REMOTE' nao encontrado no repo local."
  git -C "$ROOT_DIR" remote -v || true
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT
SERVER_WORKTREE="$TMP_DIR/server-repo"

echo "Clonando destino: $SERVER_URL ($SERVER_BRANCH)"
if git ls-remote --heads "$SERVER_URL" "$SERVER_BRANCH" | grep -q .; then
  git clone --depth 1 --branch "$SERVER_BRANCH" "$SERVER_URL" "$SERVER_WORKTREE"
elif git ls-remote --heads "$SERVER_URL" | grep -q .; then
  echo "Branch '$SERVER_BRANCH' nao encontrada. Clonando branch padrao e criando '$SERVER_BRANCH'."
  git clone --depth 1 "$SERVER_URL" "$SERVER_WORKTREE"
  git -C "$SERVER_WORKTREE" checkout -B "$SERVER_BRANCH"
else
  echo "Repositorio server sem branches. Inicializando worktree local em '$SERVER_BRANCH'."
  git init "$SERVER_WORKTREE" >/dev/null
  git -C "$SERVER_WORKTREE" remote add origin "$SERVER_URL"
  git -C "$SERVER_WORKTREE" checkout -b "$SERVER_BRANCH" >/dev/null
fi

find "$SERVER_WORKTREE" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

copy_path() {
  local rel="$1"
  local src="$ROOT_DIR/$rel"
  local dst="$SERVER_WORKTREE/$rel"

  if [[ ! -e "$src" ]]; then
    echo "Aviso: caminho ausente e ignorado: $rel"
    return 0
  fi

  mkdir -p "$(dirname "$dst")"
  if [[ -d "$src" ]]; then
    rsync -a --delete \
      --exclude '.git/' \
      --exclude '.venv/' \
      --exclude '__pycache__/' \
      --exclude '*.pyc' \
      --exclude '*.pyo' \
      --exclude '.env' \
      --exclude '*.log' \
      --exclude '*.log.*' \
      --exclude 'tokens.json' \
      --exclude 'certificado.tar.gz' \
      "$src/" "$dst/"
  else
    cp -f "$src" "$dst"
  fi
}

ALLOWED_PATHS=(
  "server"
  "flageemonitor/README.md"
  "flageemonitor/docs"
  "flageemonitor/contracts"
  "flageemonitor/server"
)

for p in "${ALLOWED_PATHS[@]}"; do
  copy_path "$p"
done

cat > "$SERVER_WORKTREE/SERVER_MANIFEST.txt" <<MANIFEST
Generated by: flageemonitor/tools/release/promote_server.sh
Source repo: $(git -C "$ROOT_DIR" remote get-url origin 2>/dev/null || echo unknown)
Source commit: $(git -C "$ROOT_DIR" rev-parse HEAD)
Source short:  $(git -C "$ROOT_DIR" rev-parse --short HEAD)
Generated at:  $(date -u +"%Y-%m-%dT%H:%M:%SZ")

Allowed paths:
$(printf '%s\n' "${ALLOWED_PATHS[@]}")
MANIFEST

FORBIDDEN_PATH_PATTERNS=(
  "proxy/sources"
  "proxy/runtime"
  "flageemonitor/proxy"
  "server/ws/.venv"
  "server/ws-dash/.venv"
)

for pat in "${FORBIDDEN_PATH_PATTERNS[@]}"; do
  if find "$SERVER_WORKTREE" -path "$SERVER_WORKTREE/$pat" -print -quit | grep -q .; then
    echo "Conteudo proibido detectado no server: $pat"
    exit 1
  fi
done

if rg -n "ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN (RSA|OPENSSH|EC) PRIVATE KEY-----" "$SERVER_WORKTREE" >/dev/null 2>&1; then
  echo "Possivel segredo detectado no staging de server. Abortando."
  rg -n "ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN (RSA|OPENSSH|EC) PRIVATE KEY-----" "$SERVER_WORKTREE" || true
  exit 1
fi

if find "$SERVER_WORKTREE" \
  \( -name '.env' -o -name '*.log' -o -name '*.log.*' -o -name '*.pyc' -o -name '*.pyo' \) \
  -print -quit | grep -q .; then
  echo "Arquivos temporarios/sensiveis detectados no staging de server. Abortando."
  find "$SERVER_WORKTREE" \
    \( -name '.env' -o -name '*.log' -o -name '*.log.*' -o -name '*.pyc' -o -name '*.pyo' \) \
    | sed -n '1,20p'
  exit 1
fi

if find "$SERVER_WORKTREE" \
  \( -name 'tokens.json' -o -name 'certificado.tar.gz' \) \
  -print -quit | grep -q .; then
  echo "Arquivos sensiveis detectados no staging de server. Abortando."
  find "$SERVER_WORKTREE" \( -name 'tokens.json' -o -name 'certificado.tar.gz' \) | sed -n '1,20p'
  exit 1
fi

pushd "$SERVER_WORKTREE" >/dev/null

if [[ -z "$(git config user.email || true)" ]]; then
  git config user.email "$(git -C "$ROOT_DIR" config user.email || echo 'release-bot@flagee.local')"
fi
if [[ -z "$(git config user.name || true)" ]]; then
  git config user.name "$(git -C "$ROOT_DIR" config user.name || echo 'Flagee Release Bot')"
fi

git add -A
if git diff --cached --quiet; then
  echo "Nenhuma mudanca para promover."
  exit 0
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "Dry-run habilitado: mudancas preparadas, sem commit."
  git status --short
  exit 0
fi

COMMIT_MSG="release(server): sync from $(git -C "$ROOT_DIR" rev-parse --short HEAD)"
git commit -m "$COMMIT_MSG"

echo "Commit criado no staging de server:"
git --no-pager log --oneline -1

if [[ "$PUSH_CHANGES" -eq 1 ]]; then
  git push origin "$SERVER_BRANCH"
  echo "Push realizado para origin/$SERVER_BRANCH"
else
  echo "Push nao realizado (modo seguro). Use --push para publicar."
fi

popd >/dev/null
