#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
DEV_REMOTE_DEFAULT="flageemonitor-proxy-dev"
DEV_BRANCH_DEFAULT="main"
PUSH_CHANGES=0
DRY_RUN=0
DEV_REMOTE="${DEV_REMOTE_DEFAULT}"
DEV_BRANCH="${DEV_BRANCH_DEFAULT}"

usage() {
  cat <<USAGE
Uso:
  $0 [--dev-remote NAME] [--dev-branch BRANCH] [--push] [--dry-run]

Descricao:
  Promove conteudo do proxy (ambiente DEV) para o repositorio flageemonitor-proxy-dev
  com allowlist e validacoes de seguranca.

Opcoes:
  --dev-remote NAME      Remote git de destino (default: ${DEV_REMOTE_DEFAULT})
  --dev-branch NAME      Branch de destino (default: ${DEV_BRANCH_DEFAULT})
  --push                 Faz push ao final (default: desabilitado)
  --dry-run              Gera staging e validacoes, sem commit
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dev-remote)
      DEV_REMOTE="$2"
      shift 2
      ;;
    --dev-branch)
      DEV_BRANCH="$2"
      shift 2
      ;;
    --push)
      PUSH_CHANGES=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Argumento invalido: $1"
      usage
      exit 1
      ;;
  esac
done

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Comando obrigatorio ausente: $1"; exit 1; }
}

require_cmd git
require_cmd rsync
require_cmd rg

if ! git -C "$ROOT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Diretorio raiz nao e um repositorio git valido: $ROOT_DIR"
  exit 1
fi

DEV_URL="$(git -C "$ROOT_DIR" remote get-url "$DEV_REMOTE" 2>/dev/null || true)"
if [[ -z "$DEV_URL" ]]; then
  echo "Remote '$DEV_REMOTE' nao encontrado no repo local."
  git -C "$ROOT_DIR" remote -v || true
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT
DEV_WORKTREE="$TMP_DIR/proxy-dev-repo"

echo "Clonando destino: $DEV_URL ($DEV_BRANCH)"
if git ls-remote --heads "$DEV_URL" "$DEV_BRANCH" | grep -q .; then
  git clone --depth 1 --branch "$DEV_BRANCH" "$DEV_URL" "$DEV_WORKTREE"
elif git ls-remote --heads "$DEV_URL" | grep -q .; then
  echo "Branch '$DEV_BRANCH' nao encontrada. Clonando branch padrao e criando '$DEV_BRANCH'."
  git clone --depth 1 "$DEV_URL" "$DEV_WORKTREE"
  git -C "$DEV_WORKTREE" checkout -B "$DEV_BRANCH"
else
  echo "Repositorio proxy-dev sem branches. Inicializando worktree local em '$DEV_BRANCH'."
  git init "$DEV_WORKTREE" >/dev/null
  git -C "$DEV_WORKTREE" remote add origin "$DEV_URL"
  git -C "$DEV_WORKTREE" checkout -b "$DEV_BRANCH" >/dev/null
fi

find "$DEV_WORKTREE" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

copy_path() {
  local rel="$1"
  local src="$ROOT_DIR/$rel"
  local dst="$DEV_WORKTREE/$rel"

  if [[ ! -e "$src" ]]; then
    echo "Aviso: caminho ausente e ignorado: $rel"
    return 0
  fi

  mkdir -p "$(dirname "$dst")"
  if [[ -d "$src" ]]; then
    rsync -a --delete \
      --exclude '.git/' \
      --exclude '.venv/' \
      --exclude '__pycache__/' \
      --exclude '*.pyc' \
      --exclude '*.pyo' \
      --exclude '.env' \
      --exclude '*.log' \
      --exclude '*.log.*' \
      "$src/" "$dst/"
  else
    cp -f "$src" "$dst"
  fi
}

ALLOWED_PATHS=(
  "proxy/sources"
  "proxy/scripts"
  "proxy/docker"
  "proxy/runtime"
  "proxy/requirements.txt"
  "proxy/utilities"
  "proxy/host-linux"
  "proxy/postgresql"
  "assets/certi_api.pem"
  "flageemonitor/README.md"
  "flageemonitor/docs"
  "flageemonitor/contracts"
  "flageemonitor/proxy"
  "flageemonitor/tools/release"
)

for p in "${ALLOWED_PATHS[@]}"; do
  copy_path "$p"
done

cat > "$DEV_WORKTREE/DEV_MANIFEST.txt" <<MANIFEST
Generated by: flageemonitor/tools/release/promote_proxy_dev.sh
Source repo: $(git -C "$ROOT_DIR" remote get-url origin 2>/dev/null || echo unknown)
Source commit: $(git -C "$ROOT_DIR" rev-parse HEAD)
Source short:  $(git -C "$ROOT_DIR" rev-parse --short HEAD)
Generated at:  $(date -u +"%Y-%m-%dT%H:%M:%SZ")

Allowed paths:
$(printf '%s\n' "${ALLOWED_PATHS[@]}")
MANIFEST

FORBIDDEN_PATH_PATTERNS=(
  "server"
  "flageemonitor/server"
  "proxy/.venv"
  "proxy/sources/__pycache__"
)

for pat in "${FORBIDDEN_PATH_PATTERNS[@]}"; do
  if find "$DEV_WORKTREE" -path "$DEV_WORKTREE/$pat" -print -quit | grep -q .; then
    echo "Conteudo proibido detectado no proxy-dev: $pat"
    exit 1
  fi
done

if rg -n "ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN (RSA|OPENSSH|EC) PRIVATE KEY-----" "$DEV_WORKTREE" >/dev/null 2>&1; then
  echo "Possivel segredo detectado no staging de proxy-dev. Abortando."
  rg -n "ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN (RSA|OPENSSH|EC) PRIVATE KEY-----" "$DEV_WORKTREE" || true
  exit 1
fi

if find "$DEV_WORKTREE" \
  \( -name '.env' -o -name '*.log' -o -name '*.log.*' -o -name '*.pyc' -o -name '*.pyo' \) \
  -print -quit | grep -q .; then
  echo "Arquivos temporarios/sensiveis detectados no staging de proxy-dev. Abortando."
  find "$DEV_WORKTREE" \
    \( -name '.env' -o -name '*.log' -o -name '*.log.*' -o -name '*.pyc' -o -name '*.pyo' \) \
    | sed -n '1,20p'
  exit 1
fi

pushd "$DEV_WORKTREE" >/dev/null

if [[ -z "$(git config user.email || true)" ]]; then
  git config user.email "$(git -C "$ROOT_DIR" config user.email || echo 'release-bot@flagee.local')"
fi
if [[ -z "$(git config user.name || true)" ]]; then
  git config user.name "$(git -C "$ROOT_DIR" config user.name || echo 'Flagee Release Bot')"
fi

git add -A
if git diff --cached --quiet; then
  echo "Nenhuma mudanca para promover."
  exit 0
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "Dry-run habilitado: mudancas preparadas, sem commit."
  git status --short
  exit 0
fi

COMMIT_MSG="release(proxy-dev): sync from $(git -C "$ROOT_DIR" rev-parse --short HEAD)"
git commit -m "$COMMIT_MSG"

echo "Commit criado no staging de proxy-dev:"
git --no-pager log --oneline -1

if [[ "$PUSH_CHANGES" -eq 1 ]]; then
  git push origin "$DEV_BRANCH"
  echo "Push realizado para origin/$DEV_BRANCH"
else
  echo "Push nao realizado (modo seguro). Use --push para publicar."
fi

popd >/dev/null
